- beta test / temp save - use rois in LUT to use only one arm call - minor changes, trace of sdk calls, fmt, ...

diff --git a/setId b/setId
--- a/setId
+++ b/setId
@@ -19,6 +19,7 @@ LIMAREV=`cd ../.. ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%
 PROCLIBREV=`cd ../../third-party/Processlib ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
 LIBCONFIGREV=`cd ../../third-party/libconfig ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
 TANGOREV=`cd ../../applications/tango ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
+SPECREV=`cd ../../applications/spec ; git log -n 1 --date=iso --format=format:"rev[%ad] head[%h][%H] ref[%d]" HEAD || echo "ERROR"`
 
 {
 echo "#define        PCO_GIT_VERSION \"\$Id:       PCO ${PCOREV} at [${DT}] \$\"" 
@@ -26,6 +27,7 @@ echo "#define       LIMA_GIT_VERSION \"\$Id:      LIMA ${LIMAREV} at [${DT}] \$\
 echo "#define    PROCLIB_GIT_VERSION \"\$Id:   PROCLIB ${PROCLIBREV} at [${DT}] \$\"" 
 echo "#define  LIBCONFIG_GIT_VERSION \"\$Id: LIBCONFIG ${LIBCONFIGREV} at [${DT}] \$\"" 
 echo "#define      TANGO_GIT_VERSION \"\$Id:     TANGO ${TANGOREV} at [${DT}] \$\"" 
+echo "#define       SPEC_GIT_VERSION \"\$Id:      SPEC ${SPECREV} at [${DT}] \$\"" 
 } > ${FILE}
 
 cat ${FILE}
